### ISSUE TITLE
Flip heat map axis

### ISSUE THREAD

**Issue by MathewBiddle** [Ocean-Science-Analytics/biosound-exploratory-project#1]
![image](https://github.com/Ocean-Science-Analytics/biosound-exploratory-project/assets/8480023/0c22e343-b69b-4a1f-bd79-c424f63d4220)

currently x = time, y = day. It is recommended to flip these to more easily visualize circadian rhythm.

**Comment by lizferguson5** [comment]
Axes have been resolved! Thanks for this reminder!
